# Generated by Django 5.1.2 on 2024-11-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('department', models.CharField(choices=[('HR', 'Human Resources'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('IT', 'Information Technology'), ('Sales', 'Sales'), ('Operations', 'Operations'), ('Admin', 'Admin')], max_length=100)),
                ('roles', models.CharField(choices=[('Manager', 'Manager'), ('Developer', 'Developer'), ('Tester', 'Tester'), ('Project Manager', 'Project Manager'), ('Team Lead', 'Team Lead'), ('Designer', 'Designer')], max_length=100)),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
